export const luxuryGoodsAnyURL = '/stats/prices/TREASURE_AVALON_RARITY1,TREASURE_AVALON_RARITY2,TREASURE_AVALON_RARITY3'

export const luxuryGoodsBridgewatchURL = '/stats/prices/TREASURE_TRIBAL_RARITY1,TREASURE_TRIBAL_RARITY2,TREASURE_TRIBAL_RARITY3'

export const luxuryGoodsCaerleonURL = '/stats/prices/TREASURE_RITUAL_RARITY1,TREASURE_RITUAL_RARITY2,TREASURE_RITUAL_RARITY3'

export const luxuryGoodsFortSterlingURL = '/stats/prices/TREASURE_DECORATIVE_RARITY1,TREASURE_DECORATIVE_RARITY2,TREASURE_DECORATIVE_RARITY3'

export const luxuryGoodsLymhurstURL = '/stats/prices/TREASURE_SILVERWARE_RARITY1,TREASURE_SILVERWARE_RARITY2,TREASURE_SILVERWARE_RARITY3'

export const luxuryGoodsMartlockURL = '/stats/prices/TREASURE_KNOWLEDGE_RARITY1,TREASURE_KNOWLEDGE_RARITY2,TREASURE_KNOWLEDGE_RARITY3'

export const luxuryGoodsThetfordURL = '/stats/prices/TREASURE_CEREMONIAL_RARITY1,TREASURE_CEREMONIAL_RARITY2,TREASURE_CEREMONIAL_RARITY3'
