export const materialsEssenceURL = '/stats/prices/T4_ESSENCE_POTION,T4_ESSENCE,T5_ESSENCE_POTION,T5_ESSENCE,T6_ESSENCE_POTION,T6_ESSENCE,T7_ESSENCE_POTION,T7_ESSENCE,T8_ESSENCE_POTION,T8_ESSENCE'

export const materialsOtherURL = '/stats/prices/T6_MOUNTUPGRADE_GIANTSTAG_XMAS,UNIQUE_MOUNTUPGRADE_RAM_XMAS,T5_MOUNTUPGRADE_HORSE_CURSE,T8_MOUNTUPGRADE_HORSE_CURSE,T8_MOUNTUPGRADE_COUGAR_KEEPER,T5_MOUNTUPGRADE_HORSE_MORGANA,T8_MOUNTUPGRADE_HORSE_MORGANA,T1_SEAWEED@0,T8_FISH_SALTWATER_ALL_BOSS_SHARK@0,QUESTITEM_TOKEN_AVALON,UNIQUE_GVGTOKEN_GENERIC'

export const materialsRelicURL = '/stats/prices/T4_RELIC,T4_SHARD_AVALONIAN,T5_RELIC,T5_SHARD_AVALONIAN,T6_RELIC,T6_SHARD_AVALONIAN,T7_RELIC,T7_SHARD_AVALONIAN,T8_RELIC,T8_SHARD_AVALONIAN'

export const materialsRuneURL = '/stats/prices/T4_RUNE,T5_RUNE,T6_RUNE,T7_RUNE,T8_RUNE'

export const materialsSoulURL = '/stats/prices/T4_SOUL,T5_SOUL,T6_SOUL,T7_SOUL,T8_SOUL'
